### ISSUE TITLE
Олег, выложи механику

### ISSUE THREAD

**Issue by kotenev** [NetBUG/mini-turty#2]
Приветствую. По договорённости в чате "ros meetup 2019" создал этот issue :-)

**Comment by NetBUG** [comment]
Вспомнил, что у меня есть удалённый доступ))
Выложил в ветку `hw`, в подкаталог `mini-turty3/hw`.
Фотографии, чертёж модуля с RPi и лидаром, полноценную прошивку BMS выложу, когда приеду в Москву.
Привод с ременной передачей и подвеской, видимо, в январе.
